language: php
php:
  - '7.2'

before_script:
  - mkdir -p build/logs
  - composer install

script:
  - ./vendor/bin/phpunit -c ./phpunit.xml.dist

after_success:
  - travis_retry php vendor/bin/php-coveralls